server:
  port: 8082

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://localhost:3306/ecom_product #?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: "@7090494731Kr"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # RabbitMQ config (default local)
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#
#custom:
#  rabbit:
#    exchange: product.exchange
