server:
  port: 8084

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://localhost:3306/ecom_inventory
    username: root
    password: "@7090494731Kr"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
